name: Uro Development x86_64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: hexpm/elixir:1.12.3-erlang-24.0.5-ubuntu-focal-20210325

    services:
      cockroachdb:
        image: cockroachdb/cockroach:v21.1.7
        env:
          COCKROACH_DATABASE: uro_dev
          COCKROACH_USER: root
          COCKROACH_PASSWORD: ''
        ports:
          - 26257:26257
        options: >-
          start-single-node --insecure

    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-deps-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-deps-

      - name: Install dependencies
        run: mix deps.get

      - name: Compile code
        run: mix compile

      - name: Run tests
        run: mix test

      - name: Check formatted code
        run: mix format --check-formatted
